# TODO: fix toc issue
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "polyidiot"
repo_name: "Arixv-TQFT"
show_authors: False # This will now control if authors are shown in Markdown
show_links: False   # This will now control if PDF/Code links are shown in Markdown
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: True

# file paths
json_readme_path: './docs/TQFT-arxiv-daily.json'
json_gitpage_path: './docs/TQFT-arxiv-daily-web.json'
json_wechat_path: './docs/TQFT-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "TQFT, Topological order, Generalized symmetry":
        filters: [ "TQFT",
                  "Topological Field Theory",
                  "Topological Quantum Field Theory",
                  "Topological defect",
        "Homotopical quantum field theory",
        "Tube algebra",
        "Quasi-local algebra",
        "Honeycomb Floquet code",
        "Gravitational anomaly",
        "Multifusion String-net",
        "Tutaev-Viro",
        "Reshetikhin-Turaev",
        "Chern-Simons theory",
        "Topological Order",
        "Topological Entanglement Entropy",
        "Toric Code",
        "Quantum Double Model",
        "Levin-Wen Model",
        "Walker-Wang Model",
        "Anyon",
        "Symmetry-protected Topological Phase",
        "Symmetry-enriched topological Phase",
        "Fractional Statistics",
        "String-net Model",
        "Modulated symmetry",
        "Topological Field Theory",
        "Topological Quantum Field Theory",
        "Tube algebra",
        "Levin-Wen string-net",
        "Topological Quantum Computation",
        "Topological Code",
        "Topological Quantum Error-Correction",
        "X-cube model",
        "Haah cubic code",
        "XZZX surface code",
        "SymTFT",
        "higher-form symmetry",
        "fusion category symmetry",
        "Hopf algebra", 
        "weak Hopf algebra", 
        "Symmetry TFT",
        "SPT",
        "SET",
        "Haagerup fusion category symmetry",
        "Haagerup CFT",
        "Anyonic chain",
        "Golden chain",
        "categorical symmetry",
        "Cluster state model",
        "Cluster ladder model",
        "Gauging non-invertible symmetry",
        "Gauging symmetry",
        "Orbifold CFT",
        "Subsystem symmetry",
        "Mixed state topological order",
        "anyon condensation",
        "fermionic topological order",
        "fermionic TQFT",
        "Fermionic topological order",
        "Fermionic TQFT",
        "Topological defect line"]