# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "polyidiot"
repo_name: "Arixv-TQFT"
show_authors: False
show_links: False
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/TQFT-arxiv-daily.json'
json_gitpage_path: './docs/TQFT-arxiv-daily-web.json'
json_wechat_path: './docs/TQFT-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
<<<<<<< HEAD
    "TQFT and Topological order": 
=======
    "TQFT":
        filters: ["TQFT", "Topological Field Theory", "Topological Quantum Field Theory",
        "Topological defect", "Homotopical quantum field theory", 
        "Gravitational anomaly",
        "Chern-Simons theory"]
    "Topological order": 
>>>>>>> 38d52e72e36046d883514838933d3068baf38b69
        filters: ["Topological Order", "Topological Entanglement Entropy", 
        "Toric Code", "Quantum Double Model", "Levin-Wen Model", "Walker-Wang Model",
        "Anyon", "Symmetry-protected Topological Phase",
        "Symmetry-enriched topological Phase",
        "Fractional Statistics", 
<<<<<<< HEAD
        "String-net Model", "TQFT", "Topological Field Theory", 
        "Topological Quantum Field Theory", 
        "Topological Quantum Computation","Topological Code",
=======
        "String-net Model"]
    "Topological Quantum Computation":
        filters: ["Topological Quantum Computation","Topological Code",
>>>>>>> 38d52e72e36046d883514838933d3068baf38b69
                  "Topological Quantum Error-Correction"]
    "Fracton":
        filters: ["X-cube model", "Haah cubic code", "XZZX surface code"]
