title: Mathematical Physics arXiv Daily
description: Daily automatic collection of arXiv preprints on TQFT, topological order, and generalized symmetries. By Zhian Jia.
show_downloads: False

# github:
#   zip_url: https://github.com/polyidiot/Arxiv-TQFT
#   another_url: https://github.com/polyidot/Arxiv-TQFT

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
