name: Run Arxiv Papers Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours

env:
  GITHUB_USER_NAME: polyidiot
  GITHUB_USER_EMAIL: giannjia@foxmail.com

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Python Env
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install arxiv
        pip install requests
        pip install pyyaml
        
    - name: Run daily arxiv
      run: |
        python daily_arxiv.py
        
    - name: Push new Arxiv-TQFT.md
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Github Action Automatic Update TQFT Arxiv Papers"
        files: README.md docs/TQFT-arxiv-daily.json docs/TQFT-arxiv-daily-web.json docs/index.md docs/TQFT-arxiv-daily-wechat.json docs/wechat.md
        rebase: 'true'
        name: ${{ env.GITHUB_USER_NAME }}
        email: ${{ env.GITHUB_USER_EMAIL }}
